POST http://localhost:3001/api/patients
content-type: application/json

{
  "name": "max",
  "gender": "male",
  "entries": [],
  "occupation": "none"
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
content-type: application/json

{
  "type": "HealthCheck",
  "description": "none",
  "specialist": "Dr House",
  "diagnosisCodes": [],
  "healthCheckRating": 0,
  "date": "1984-20-23"
}
